### PR TITLE
Indicator: misc bug fixes

### PR DESCRIPTION
**Pull request by xingruoxicic**
- ensure text label is centre at all time
- Large number indicator size should be 28 x 28px
Small number indicator size should be 24 x 24px

- When user has selected number indicator but changes it to text, the indicator should automatically update to the default text indicator and vice versa
- Number indicator should not have icon variable
- Large size use body 3 text for all

### CODE REVIEW

**Review by MikeJalow — APPROVED** [review]

**Comment by Keyur-Trivedi** [comment]
Everything looks good. 
Only thing is that I can see multiple icons when I switch between the code and maple leaf.
Can we please fix that, reloading is not an ideal option.

image

**Review by Keyur-Trivedi — CHANGES_REQUESTED** [review]
Please look in the comment.

**Comment by xingruoxicic** [comment]
> Everything looks good. Only thing is that I can see multiple icons when I switch between the code and maple leaf. Can we please fix that, reloading is not an ideal option.
> 
> image

This bug is being fixed on a separate [branch](https://github.com/IRCC-ca/ds-sdc-dev/tree/bug/icon_fix) as it's getting more complicated.

**Comment by Keyur-Trivedi** [comment]
Looks good to me. One thing still need some refactoring is when we change the icons from "Code" to Maple Leaf" and it does not we ideally want. But overall it's good to merge.

**Pull request merged**
